# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ace5117f0e007c9769b43cb5699ed2d00943ef25421c75b8870f0dd7d24e32cf3b927d9d78e2010587ab8640276464e60dadbc8c808e83a55e6a80cf8a31a10

test:
  secret_key_base: 9512abc6d0abcc45332f8a4c88f926a468a50280ab984f647b68f51583c4c60ca322e68cfa8c496c8251b2c52789b1fa8b43a1f1eb63f45486fd61657c8cb441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
